version: '3'

services:
  dev:
    env_file: development.env
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - ./app:/api/app
      - ./lib:/api/lib
    depends_on:
      - pg
      - mongo
    # Enable debugging
    tty: true
    stdin_open: true
  test:
    env_file: development.env
    build: .
    command: bundle exec rspec
    tty: true # for colored output
    depends_on:
      - pg
      - mongo
  prod:
    env_file: production.env
    build: .
    command: bundle exec rails s -b '0.0.0.0' # TODO: make this passenger probably
    depends_on:
      - pg
      - mongo

  pg: # Used for auth
    image: postgres
    volumes:
      - ./tmp/db/pg:/var/lib/postgresql/data
  mongo: # Stores pbot configuration
    image: mongo
    volumes:
      - ./tmp/db/mongo:/data/db

  # TODO
  # web:
  #   build: ../pbot-admin-web
  #   command: yarn start
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ../pbot-admin-web:/web
  #   depends_on:
  #     - api
